name: Notify Discord on Push

on:
  push:
    branches:
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Новий коміт додано: ${{ github.event.head_commit.url }}"}' ${DISCORD_WEBHOOK_URL}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
